# -*- coding: utf-8 -*-
"""Copy of ResumeAnalyzer1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YwSLdVdttJdqpekHOID5lyREXLTfyhva
"""

!pip install gradio

!pip install pdfplumber

import gradio as gr
import pdfplumber

skills = ["HTML", "CSS", "JavaScript", "Python", "Flask", "MySQL", "Bootstrap", "Git"]

def extract_text_from_pdf(pdf_file):
    text = ""
    with pdfplumber.open(pdf_file) as pdf:
        for page in pdf.pages:
            text += page.extract_text() or ""
    return text.lower()

def analyze_resume(pdf_file, job):
    resume_text = extract_text_from_pdf(pdf_file)
    job = job.lower()

    matched = []
    missing = []

    for skill in skills:
        s = skill.lower()
        if s in job and s in resume_text:
            matched.append(skill)
        elif s in job and s not in resume_text:
            missing.append(skill)

    total = len(matched) + len(missing)
    percent = round((len(matched) / total) * 100) if total > 0 else 0

    return ", ".join(matched), ", ".join(missing), f"{percent}%"

app = gr.Interface(
    fn=analyze_resume,
    inputs=[
        gr.File(label="Upload Resume (PDF)"),
        gr.Textbox(lines=6, label="Paste Job Description")
    ],
    outputs=[
        gr.Textbox(label="Matched Skills"),
        gr.Textbox(label="Missing Skills"),
        gr.Textbox(label="Match Percentage")
    ],
    title="Smart Resume Analyzer",
    description="Upload a resume PDF and compare it with a job description"
)

app.launch(share=True)



To run this use link-- b238be3bd1b6cb5c57.gradio.live